apiVersion : apps/v1
kind: Deployment
metadata:
  name: "heroescluster-201d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "heroescluster-201d"
  template:
    metadata:
      labels:
        app: "heroescluster-201d"
    spec:
      containers:
        - name: "heroescluster-201d"
          image: "heroes.azurecr.io/heroescluster"
          ports:
          - containerPort: 3000